### ISSUE TITLE
import pointing to index.d.ts with example export

### ISSUE THREAD

**Issue by rosnk** [react-native-elements/react-native-elements-universe#12]
**Explain what you did (Required)**
tried to import "CircularSlider" but there is no export in installed repository 

trying to use "CircularSlider" component

**Expected behavior (Required)**
I should get "CircularSlider" component currently getting undefined component. 

I expect to get CircularSlider component which i can use in my expo app.

**Describe the bug (Required)**
`import { CircularSlider } from 'react-native-elements-universe';`
this statement is pointing to : index..ts which has following content: 
```
import Example from './Example';
export { Example };

```

looks like wrong export ??

**Comment by arpitBhalla** [comment]
This component isn't yet released

**Comment by arpitBhalla** [comment]
Try
npm install https://github.com/react-native-elements/react-native-elements-universe#dist

**Comment by rosnk** [comment]
@arpitBhalla thanks!
